<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>then-catch 区别</title>
</head>
<body>

</body>
<script src="../jquery-3.2.1.min.js"></script>
<script type="text/javascript">
    function throwError(value) {
        // 抛出异常
        throw new Error(value);
    }
    // <1> onRejected不会被调用
    function badMain(onRejected) {
        return Promise.resolve(42).then(throwError, onRejected);
    }
    // <2> 有异常发生时onRejected会被调用
    function goodMain(onRejected) {
        return Promise.resolve(42).then(throwError).catch(onRejected);
    }
    // 运行示例
    badMain(function(){
        console.log("BAD");
    });
    goodMain(function(){
        console.log("GOOD");
    });
    /**
     *执行结果为  GOOD
     *
     * 使用promise.then(onFulfilled, onRejected) 的话，在 onFulfilled 中发生异常的话，在 onRejected 中是捕获不到这个异常的。

     * 在 promise.then(onFulfilled).catch(onRejected) 的情况下，then 中产生的异常能在 .catch 中捕获

     * .then 和 .catch 在本质上是没有区别的，但需要分场合使用。
     *
     * */
</script>
</html>